src/zproto_client_c.gsl, src/zproto_codec_c.gsl
You can now copy/paste fields from the protocol model into the client methods.
=> Problem: client stack did not support all field types

README.md, src/main/java/org/zproto/ZprotoExample.java, src/zproto_bnf.gsl, src/zproto_example.bnf, src/zproto_example.c, src/zproto_server_c.gsl
Also renamed CONFIGURE -> LOAD (kept old name for compatibility)
=> Added SAVE method for server config data

src/zproto_server_clj.gsl
Solution: filter out internal events for now, so generated code can compile.
=> Problem: clojure state machine handles internal events incorrectly

src/zproto_server_c.gsl
Solution: report this; it helps debug security logic.
=> Problem: server does not say what security mechanism it's using

src/goczmq/zproto/example/binary.go, src/goczmq/zproto/example/log.go, src/goczmq/zproto/example/structures.go, src/goczmq/zproto/example/types.go, src/zproto_codec_go.gsl
* Modified zproto_codec_gsl to match API changes to goczmq when using goczmq for zproto
=> Problem: backwards incompatible API changes in goczmq

src/zproto_bnf.gsl
Solution: use C style on field names
=> Problem: BNF does not normalize field names

README.md
Solution: fix these and some other errors in README.md.
=> Problem: README.md wrongly refers to model directory

src/zproto_client_c.gsl
=> Problem: code has tabs and comment whitespace error

src/go/zproto/example/binary.go, src/go/zproto/example/binary_test.go, src/go/zproto/example/example.go, src/go/zproto/example/log.go, src/go/zproto/example/log_test.go, src/go/zproto/example/structures.go, src/go/zproto/example/structures_test.go, src/go/zproto/example/types.go, src/go/zproto/example/types_test.go, src/goczmq/zproto/example/binary.go, src/goczmq/zproto/example/binary_test.go, src/goczmq/zproto/example/example.go, src/goczmq/zproto/example/log.go, src/goczmq/zproto/example/log_test.go, src/goczmq/zproto/example/structures.go, src/goczmq/zproto/example/structures_test.go, src/goczmq/zproto/example/types.go, src/goczmq/zproto/example/types_test.go, src/zproto_codec_go.gsl
Added more comments and modified existing comments to be in correct format also changed variable names to meet go standards.
=> Problem: go codec is not golint clean

src/zproto_codec_c_v1.gsl
Reverts zeromq/zproto#218
Reverting this along with #217... sorry for that.
=> Revert "PROBLEM: forgot to remove part that was commented"

configure.ac
Solution: Remove zmq installation check - unneeded
=> Problem: zproto required zmq to be installed

src/zproto_server_c.gsl
Solution: Disable security section if != v4
=> Problem: Zproto server not compatible with ZeroMQ < v4.

src/zproto_codec_c_v1.gsl
Solution: Switch to using zsock.
Rationalle: Manual edit in Zyre, want to regenerate
=> Problem: Using deprecated zsocket api.

src/zproto_codec_c.gsl, src/zproto_example.c, src/zproto_example.xml
=> Problem: c_codec doesn't have tests for hash type

src/zproto_codec_c.gsl, src/zproto_example.c
Solution: Free the UUID in the second iteration
=> Problem: duplicated UUID doesn't exist in the second iteration

src/zproto_codec_c.gsl, src/zproto_example.c
Solution: Explicitly specify the targeted property
=> Problem: name property is referring to the wrong property

src/Makefile.am, src/go/goczmq/zproto/example/binary_test.go, src/go/goczmq/zproto/example/log_test.go, src/go/goczmq/zproto/example/structures_test.go, src/go/goczmq/zproto/example/types_test.go, src/go/zmq4/zproto/example/binary_test.go, src/go/zmq4/zproto/example/log_test.go, src/go/zmq4/zproto/example/structures_test.go, src/go/zmq4/zproto/example/types_test.go, src/zproto_codec_go.gsl, src/zproto_lib_go.gsl, src/zproto_server_go.gsl
=>  Problem: We don't have golang port of zproto_server

src/zproto_codec_c.gsl
Solution: properly free allocated memory
=> Problem: memory leaks in virtual class codec

src/go/goczmq/zproto/example/binary.go, src/go/goczmq/zproto/example/binary_test.go, src/go/goczmq/zproto/example/example.go, src/go/goczmq/zproto/example/log.go, src/go/goczmq/zproto/example/log_test.go, src/go/goczmq/zproto/example/structures.go, src/go/goczmq/zproto/example/structures_test.go, src/go/goczmq/zproto/example/types.go, src/go/goczmq/zproto/example/types_test.go, src/zproto_codec_go.gsl
Solution: update go gsl template and regenerate examples.
=> Problem: goczmq constants changed

src/zproto_client_c.gsl
Solution: Properly free temporary variable memory
=> Problem: Memory leak in handling zuuid_t filed type

autogen.sh, src/main/java/org/zproto/ZprotoExample.java, src/zproto_codec_java.gsl
Changed implemented interface in zproto_codec_java.gsl from deprecated java.io.Closeable to java.lang.AutoCloseable. 
Updated autogen.sh to use libtoolize rather than libtool.
=> Changed from deprecated java.io.Closeable to java.lang.AutoCloseable

autogen.sh
Solution: revert back to libtool in autogen.sh.
=> Problem: libtoolize is not standard on all platforms.

src/zproto_server_c.gsl
Solution: revert that change...
=> Problem: raising minimum server timeout broke some apps

src/zproto_client_c.gsl, src/zproto_codec_c.gsl
=> Problem: event name copy/paste typo

src/csharp/ZProto.Tests/ExampleTests.cs, src/csharp/ZProto/Example.cs, src/zproto_codec_cs.gsl, src/zproto_example_cs.xml
this confusing as you cannot know from intellisense which field belong to which message.
This pull request create a different class for each message.
Although this is breaking change for the netmq codec no body is using the codec yet.
=> problem: in netmq codec all messages field are in same class

src/zproto_codec_c.gsl
Solution: generate selftest function as void
=> Problem: codec selftest function not compatible witj zpoject

src/zproto_server_c.gsl
=> Problem: int to bool warning on Windows

Dockerfile
=> Problem: zproto does not have a Dockerfile

src/zproto_client_c.gsl
Solution: finish generation of methods and such.
Test case is Malamute.
=> Problem: not generating a valid API model for client

src/zproto_client_c.gsl
Solution: Check byref attribute and set by_reference if needed.
=> Problem: By Reference not checked for methods when generating api file

src/zproto_codec_c.gsl, src/zproto_codec_c_v1.gsl
Solution: fix code in PUT_NUMBER1
=> Problem: integer truncation warnings on Windows

src/zproto_client_c.gsl
Solution: now reply would be fred every time
=> Problem: potential memory leak

src/zproto_client_c.gsl
=> Problem: s_accept_reply is actually a blocking call without time out

src/zproto_server_c.gsl
=> Problem: free is used

autogen.sh
Thanks to http://stackoverflow.com/a/15448876/3075972
=> Allow to build on OSX

src/Makefile.am, src/zproto_client_c.gsl, src/zproto_dot.gsl, src/zproto_server_c.gsl
Solution: generate graphviz diagram from client and server models
=> Problem: malamute state diagrams are hard to understand

src/zproto_server_c.gsl
Solution: use zconfig_get instead
=> Problem: zconfig_resolve is deprecated

src/zproto_server_c.gsl
Solution: Add server_configuration callback
=> Problem: Server custom part has no way to react to configuration changes

src/zproto_codec_c.gsl, src/zproto_server_c.gsl
Closes #320. (we should update the README)
=> Handle malformed messages better

src/zproto_codec_c_v1.gsl
Solution: add new constructor
Testing is TBD
=> Problem: can't load zpl encoded message

src/zproto_codec_c_v1.gsl
Solution: add a test + fix bugs found by the testing.
=> Problem: _zpl and _new_zpl are not tested

src/zproto_codec_c.gsl
Solution: assert for correct number of items in aux, code above adds
only Name: Brutus in this case
=> Problem: make check fails for zproto_codec_c codecs

AUTHORS, src/zproto_codec_c.gsl
=> Problem: generated code build fails with older GCC

src/zproto_codec_c_v1.gsl
Solution: generate zproto API model
Note that model is not tested (yet) and script generates model and header file, so there might be a conflict in zproject workflow. However I'll figure those issues later on.
=> Problem: there's no API model for generated coded_c_v1

src/zproto_codec_c_v1.gsl
Solution: fix all the issues.
passed make check on https://github.com/42ity/fty-proto/
BTW: I was surprised that adding API model integrated well with zproject. My kudos to ppl developing this! make code worked on the first round
=> Problem: generated API model does not work

src/zproto_codec_c_v1.gsl
=> Problem: generated declarations of fty-proto are still not usable

src/zproto_codec_python.gsl
Solution: fix the variable name
=> Problem: numeric fields are not dumped correctly

src/zproto_codec_c.gsl
=> Problem: there is no way to create a deepcopy of a message instance

src/zproto_codec_c_v1.gsl, src/zproto_example.xml, src/zproto_lib.gsl
* only generate API file is model calls is not private
* set package_dir according to zproject's class properties
=> zproject compatability enhancements

src/zproto_codec_c.gsl, src/zproto_codec_c_v1.gsl
* Fixed memory leak
* Deal with private switch set by zproject
* Bugfix for predefined values
=> codec c improvements and bugfixes

README.md
=> Problem: README.md out of date with gitdown

src/zproto_codec_c.gsl
Solution: make new_zpl compatible with czmq (4) again
=> Problem: can't build malamute using latest zproto

src/zproto_codec_c.gsl
=> Problem: Missing } in class__new_zpl constructor generates invalid code

src/fsharp/ZProto.Tests/ExampleTests.fs, src/fsharp/ZProto/Example.fs, src/zproto_codec_fs.gsl, src/zproto_example_fs.xml, src/zproto_lib_fs.gsl
solution add support for fsharp using FsNetMQ binding for netmq.
https://github.com/netmq/FsNetMQ
=> problem: no fsharp support

src/Makefile.am
Solution: add it to src/Makefile.am
=> Problem: zproto_codec_cs is not installed as part of the build

src/zproto_server_c.gsl
Solution: save in self->port like with the interactive BIND command
=> Problem: binding server through config does not save port

src/zproto_codec_c.gsl
Solution: change condition to be more explicit what we want to :)
=> Problem: codec API file not regenerated after make code

README.md, README.txt
=>  Problem: mismatch for server/timeout in docs

src/zproto_dot.gsl
Solution: If there is message defined, put it in brackets like "send (ok)"
=> Problem: send method in diagram is not conclusive

src/zproto_server_c.gsl
=> Problem: typo in documentation

src/zproto_codec_c.gsl
Solution: propagate them, so generated code is commented
=> Problem: codec define comments are not propagated to API model

src/zproto_client_c.gsl
Solution: Free those types before accepting another message first destroy them
=> Problem: zproto_client leak memory of long string, chunk and frame

src/zproto_codec_c.gsl
Solution: Add a flag to indicate if codec if for pubsub.
In case of pubsub, a topic will be prefixed to every message.
=> Problem: codec doesn't support pubsub messaging

src/zproto_codec_c.gsl
=> Problem: Pubsub is leaking the topic

src/zproto_codec_c.gsl
=> Problem: Pubsub leaking the topic

src/zproto_codec_c.gsl
=> Problem: generated code yield some warnings

src/zproto_codec_c.gsl, src/zproto_lib.gsl
=> Problem: Pubsub was default to true

src/zproto_example.xml, src/zproto_example_java.xml
=> Problem: The new pubsub flag is undocumented

src/zproto_codec_c.gsl
Solution: When receiving from XPUB socket, the codec read the id and topic from the subscription
=> Problem: No way to recv from XPUB socket

src/zproto_codec_java.gsl
Solution: When receiving from XPUB socket, the codec read the id and
topic from the subscription
=> Problem: [java] No way to recv from XPUB socket

src/zproto_codec_java.gsl
=> Problem: Missing import for List and ArrayList

.travis.yml
Solution: update repository url
=> Problem: travis still using precise packages in xenial

src/zproto_codec_c.gsl, src/zproto_lib.gsl
Solution: add the ability to use zmq_msg_t which is stack-based
=> Problem: zframe_t require dynamic allocation

src/zproto_codec_java.gsl
zproto_codec_java was not support virtual option,and now will generate both virtual and non virtual method.
=> Feature codec java
