- src/zproto_client_c.gsl
The use of a method to enable verbose tracing is poor, as it cannot
trace construction (where problems do happen frequently).
Solution: remove $(client.name)_verbose method and replace with a
global variable, one per class, that can be set true/false before
creating any instances.
> Problem: can't trace client constructor

- src/zproto_client_c.gsl
...oid)`
Solution: Don't emit `void` when preceded by a `self` in the arguments
> Problem: client constructor with no args generates `$(class)_new(self, void)`

- README.md
- src/zproto_client_c.gsl
- src/zproto_server_c.gsl
Solution: Support the `before` and `after` model elements.
Resolves #195.
> Problem: Need a non-redundant way to specify transition actions by state.

- src/zproto_client_c.gsl
Solution: add more logging in the GSL code generator
> Problem: the generated client bindings do not do any logging for messages with no actions

- src/zproto_codec_c.gsl
- src/zproto_codec_c_v1.gsl
Problem: Generated C++ code causes GCC to complain (-Wunused-variable) about the "bool verbose" in *_test() methods.
Solution: Make up artificial usage for the variable, which might be really used later, to satisfy the compiler.
> Silence "unused" warning from compiler in generated C/C++ code

- src/zproto_codec_c.gsl
Look like check of uuid message tyupe was lost in new version of C library generation script.
This commit add it back.
It also silence compiler in -Wall mode about unused varibles.
> readd lost check of uuid

- src/zproto_codec_c.gsl
As described in #203 if a field comment was multiline this would
cause the code to not compile.
This was due to comments being started with //.
This commits update the gsl script to write comment with
the /* .. */ syntax instead.
This fixes #203.
> Fields' comments can now be multiline.

- doc/zproto_example.txt
- src/zproto_client_c.gsl
The constructor is used to also connect to servers. This is neat except
that when it fails, the constructor fails, and there is no way to return
status information to the caller.
Solution: constructor should only initialize object. The connect method
should be done seperately.
- Removed support for "constructor" as special method in GSL code
- Removed call to constructor method, in class constructor
Note: this breaks existing client models and code. The fix is simple.
1. rename "constructor" to "connect" in XML model
2. in all calls to xxx_new, remove arguments
3. add second call to xxx_connect, with connection arguments
4. test return code 0/-1 from that method
See Malamute mlm_client as example.
Fixes #208
> Problem: zproto client constructor does too much

- src/zproto_codec_c_v1.gsl
float numbers from hash fields, which would make it clear which state is
successfull, erroneous and which would distunguish between error states.
SOLUTION: add them.
- Tests included.
> PROBLEM: There is no convenient wrapper to get signed, unsigned and

- src/zproto_codec_c_v1.gsl
expanded using preprocessor macro
SOLUTION: add attribute 'export_header' to element 'class' in which the
macro can be defined.
> PROBLEM: can't have value of 'export_macro' attribute (of class element)

- src/zproto_client_c.gsl
- src/zproto_codec_c.gsl
- src/zproto_codec_c_v1.gsl
- src/zproto_server_c.gsl
The generation of include guards did not fit to [the expected naming convention of the C++ language standard](https://www.securecoding.cert.org/confluence/display/cplusplus/DCL32-CPP.+Do+not+declare+or+define+a+reserved+identifier#DCL32-CPP.Donotdeclareordefineareservedidentifier-NoncompliantCodeExample%28HeaderGuard%29 "Do not use identifiers that are reserved for the compiler implementation.").
This implementation detail can be fixed by deletion of [a few underscores](http://stackoverflow.com/questions/228783/what-are-the-rules-about-using-an-underscore-in-a-c-identifier#answer-228797 "What are the rules about using an underscore in a C++ identifier?").
> Fix include guards.

- src/zproto_client_c.gsl
Using GSL + operator is unsafe when argument contains numeric value.
Solution: enclose argument in quotes.
> Problem: calculating wrong patterns for API replies

- include/zproto_example.h
- src/selftest
- src/zproto_bnf.gsl
- src/zproto_codec_c.gsl
- src/zproto_example.c
- src/zproto_example.xml
- src/zproto_lib.gsl
To test the integration of codecs now we have tests message with a digest of its frame content. Each codec can run through test messages and make sure its implementation is compatible with the
reference implementation.
To generate digests automaticly you need to first run gsl script with digest switch then the selftest script with -d swithc
gsl -digest:1 zproto_example.xml
./selftest -d
This will update zproto_example.xml file with new digests. You will need to regenerate digests if you changed the message tests in zproto_example.xml.
This chnage is backwards compatible and shouldn't break your code so please report any breaks.
> Problem: need integration tests between codecs

- src/zproto_codec_c.gsl
- does not destroy test data in iteration 2
- leaves dangling string in test zmsgs (popstr w/o free)
- zmsg test sends Hello, World and expects Captcha Diem
Solution: fixed and tested.
> Problem: several issues in C selftest

- src/zproto_client_c.gsl
Solution: add to s_satisfy_pedantic_compilers().
> Problem: engine_set_connected() can raise compiler warning

- src/zproto_server_go.gsl
Solution: Do not kill the handler loop by returning error, just log the error
> Problem: Pipe handler stops when unexpected error happens

- src/zproto_client_c.gsl
The "i" picture expects int, whereas the method is providing a bool.
This results in rather nasty heap corruption.
Solution: use int and cast to bool.
> Problem: _connected method is corrupting memory

- src/zproto_codec_c.gsl
This is to allow encoding/decoding into zmsg structure instead of
to/from socket, for carrying over Zyre, Malamute, and similar
protocols.
Solution: if class.virtual = 1, then send/recv are virtualized and
work with zmsg_t instead of zsock_t. Since we do not need both real
and virtual encoding in the same class, this keeps the API surface
to a minimum.
Note: I've not yet tested this except to be sure it hasn't broken
existing code.
> Problem: need virtualized codec

- src/zproto_codec_c_v1.gsl
Problem:
on malformed message is_$(CLASS) function crashes on assert in zframe_data(frame).
Solution:
check whether frame is extracted
> fix is_$(class) template

- src/zproto_codec_java.gsl
Should be 'test/java' not 'main/java'.
Solution: fixed.
Problem #2: generates syntax error when using constants
Solution: fixed; removed the dangling ).
> Problem: test class is put into wrong directory

- src/zproto_codec_c.gsl
#256 changed uuid type filed handling removing possibility of zero copy ownership transfer of uuid type filed to caller.
Solution: restore old style destructive _get method for uuid type field
> Problem: we need unnecessary zuuid_dup & zuuid_destroy for transfering ownership of uuid fileld to caller

- src/zproto_codec_c.gsl
Problem: compiler complains about unused variable
Solution: remove unsused varible nbr_frames
Problem: _send on virtual class steal frame filed content
Solution: make a copy of frame on sending for virtual class
Problem: selftest is not empties and copies msg between _send and _recv for virtual class
Solution: fix selftest for virtual class
> fix virtual class

- src/zproto_client_c.gsl
Solution: revert print of class name in selftest
> Problem: over-zealous replacement of class name

- src/zproto_codec_c_v1.gsl
Solution: copy the code handling struct comments from zproto_codec_c
> Problem: zproto_codec_c_v1 produces invalid C files

- README.md
- src/zproto_client_c.gsl
- src/zproto_server_c.gsl
Note, engine_set_timeout is now deprecated in favor of engine_set_expiry. 
To do heartbeating client must use engine_set_heartbeat.
> Fixes to client heartbeating

- src/zproto_server_c.gsl
As a result the code crashes later and in opaque ways.
Solution add an assertion; if the server cannot create its router
socket then the app cannot run in any sane fashion.
> Problem: does not assert on zsock_new failure

- src/zproto_codec_c_v1.gsl
This issue occurs because the selftests have been unified and the method signature is no longer valid.
Solution: Change the return type from int to void and remove the unnecessary return.
> Problem: Using the c codec in version v1 in a zproject wont compile.

- packaging/nuget/NetMQ.zproto.nuspec
- src/zproto_codec_cs.gsl
- src/zproto_example_cs.xml
- src/zproto_lib_cs.gsl
Solution: Publish zproto to nuget. This PR adds nuget packaging.
Also allow to set a modifier (public/private) on the generated NetMQ class.
> problem: download and use ZProto with NetMQ is complicated

- src/zproto_codec_c.gsl
- src/zproto_server_c.gsl
With Reference to issue: https://github.com/zeromq/zproto/issues/285
zproto_codec_c.gsl already supports "send/recv" methods that encode messages to zmsg_t format. These methods are only generated when virtual="1" is set in the .xml referenced by the  protocol_class property.
The downside is that servers generated by zproto_server_c.gsl cannot use message classes created with the virtual flag set.
Therefore, rather than implement separate encode/decode methods that are essentially copies of the methods generated when the virtual flag, I adapted zproto_server_c.gsl so that it detects if the protocol_class has the virtual flag set and generates appropriate wrapper code to generate & send the message as one would expect.
NOTE: there were several copies of the 'send' command that were adapted …
> A version of zproto_server_c.gsl that supports "virtual" codecs

- src/zyre_peer_example/project.xml
- src/zyre_peer_example/src/example_peer.c
- src/zyre_peer_example/src/example_peer.xml
- src/zyre_peer_example/src/example_peer_msg.xml
- src/zyre_peer_example/src/test_peerd.c
- src/zyre_peer_example/src/zproto_peer_c.gsl
This is an adaptation of the zproto_client_c.gsl generator that builds a zproto based Zyre node. This generator allows the creation of zyre nodes that use the zproto state machine scheme for generating edge-net  protocols. The generator wraps and interprets zyre's messages into the user's protocol space to be dealt with through the state machine syntax.
In addition to the generator I'm providing a zproject based example, loosely based on Zyre's chat example. I'm submitting this to the zproto project because it felt like it might be a globally useful tool for other edge-net apps.
The generator and example are still a work in progress, I started building it as part of an edge-net based p2p game node. I will continue to update the generator as I develop the code further, I'm open to …
> A Zyre node generator supporting state machine protocol scripting & Example

- src/zproto_client_c.gsl
> Problem: int/boolean conversion warning on Windows

- src/zproto_client_c.gsl
Specifically, it does not generate api/*.xml for its classes.
Solution: generate api/*.xml for codec and for client. The server
API isn't needed right away.
Unfinished work in progress...
> Problem: zproto isn't compatible with zproject

- src/zproto_client_c.gsl
It was stupidly trying to cast to a private structure used in
the actor.
Solution: pass the verbose value to the actor, as for all methods.
> Problem: set_verbose was trashing memory

- src/zproto_client_c.gsl
- src/zproto_codec_c.gsl
Solution: change zproto_client_c.gsl and zproto_codec_c.gsl to
create .api files instead of .xml
> Problem: class filename ext is still xml

- Dockerfile
since zeromqorg/gsl was tuned
to accept $GSL_BUILD_DIR environment variable
Solution: Cleanup
> Problem: No need to specify WORKDIR

- README.md
This functionality used to exist and it was complex, so it was removed.
See #301.
Solution: Remove paragraph.
> Problem: README.md contains outdated paragraph about message filtering

- autogen.sh
Apparently libtool needs to be issued as libtoolize. Other packages do this also.
> Problem: libtool should be libtoolize

- src/zproto_client_c.gsl
Solution: use the signature from the src which includes the correct context
should fix #308
> Problem: set_verbose signature mismatch between src and header

- README.txt
- src/zproto_client_c.gsl
Solution: Add a new <api> tag which will be used in conjunction with
zproject to clearly distinct between the none zproject use of the
<header> tag.
Also I added a section about hand-written code in the Readme.
> Problem: Hand-written code is confusing when using zproject

- src/zproto_client_c.gsl
Solution: properly propagate zproject type and size to generated methods in .api file
> Problem: protocol msg properties type and size not propagated to .api

- src/zproto_codec_c.gsl
Solution: properly propagate class state value (stable, draft, legcy) to .api files if defined.
> Problem: class state not propagated to generated .api files

- src/zproto_codec_c.gsl
> Problem: [c,v2] missing space when printing test result

- src/zproto_client_c.gsl
Solution: add the missing semicolon
> Problem: set_verbose declaration in zproto_client_c is missing a semicolon and causing build errors

- src/zproto_codec_python.gsl
> Problem: Python codec generator is missing `self` parameter for the `id` function`

- src/zproto_client_c.gsl
Solution: use class_name_new(), class_name_set_verbose() and class_name_destroy().
> Problem: zproto_client_c's selftest uses zactors causing build errors

- src/zproto_codec_c.gsl
Solution: destroy the previous zlist, if any.
Closes #321.
> Problem: _recv from socket can leak zlist_t objects.

- src/zproto_server_c.gsl
Solution: invoke s_server_config_global after updating the configuration
> Problem: engine_configure does not apply new configuration

- src/zproto_dot.gsl
Solution: drop [gsl].shuffle = 1 line, which was apparently causing
generating of stub for handle_component_register and stub for
handle_list_components later on
fixes https://github.com/zeromq/zproto/pull/319
> Problem: dot generator broke server generator

- src/zproto_dot.gsl
Solution: merge them back to the descendant nodes, draw their actions
with dashed lines to distinguish "own" and inherited actions
cc @malanka
> Problem: inherited states messed up the graph

- src/zproto_codec_c.gsl
- src/zproto_server_c.gsl
referenced before assignment.
Solution: move the "malformed message" check a couple of lines down.
Also minor change in the message header text
This was a pretty silly mistake... CI should have caught it!
> Problem: server generator contains a syntax error and `client` is

- src/zproto_codec_c_v1.gsl
Solution: add _dump_zpl method, which creates zconfig_t from the
message. This way one can store messages in plan text.
This is more RFC, maybe code should be wrapped by something mentioning this is only draft. The function to load messahe from zconfig_t* _load_zpl (or _new_zpl) will be pushed later.
> [RFC] Problem: can't serialize generated codecs to text form

- src/zproto_codec_c_v1.gsl
Solution:
* allocate exact amount of memory
* use proper printf format instead of conditionals
Fixes review notes from https://github.com/zeromq/zproto/pull/333
> Problem: s_bytes_str is not elegant

- README.md
- README.txt
Solution: Treat XML tags as code.
> Problem: Generating Markdown from README.txt lost some XML tags.

- packaging/debian/rules
Solution: create config subdir as a workaround if building the
packages with automake < 1.14
> Problem: debian build fails with automake < 1.14

- src/zproto_codec_c_v1.gsl
Solution: rename to $(class.name)_is and provide compatibility macro
> Problem: is_$(class.name) incompatible with zproject API model

- src/zproto_codec_c.gsl
Solution: do not strdup `string` fields.
--
Derp... I should have run memcheck on my project before sending my previous PR.
> Problem: dup'ing a msg with a `string` field leaks memory.

- src/zproto_server_c.gsl
Solution: snprintf size parameter includes the NULL terminating char
as the manpage says, so don't pass sizeof(..) - 1
> Problem: build error with GCC7 in zproto_server_c generated code

- src/zproto_codec_python.gsl
I've fixed some small typo's (extra ; and ) ) and removed unused imports of uuid and struct
Also fixed some spacing and comparisons to make generated code almost fully PEP8-compliant
> Python codec: Fixed some typos, unused imports and made it more PEP8ish

- src/zproto_client_c.gsl
Solution: snprintf size parameter includes the NULL terminating char
as the manpage says, so don't pass sizeof(..) - 1
Same problem already solved for the server codec
> Problem: build error with GCC7 in zproto_client_c generated code

- src/zproto_codec_c.gsl
Solution: add a check to only strdup non-null strings
> Problem: _dup() strdup a null pointer

- src/zproto_server_c.gsl
Solution: return an identifier in engine_set_monitor(), and create
engine_cancel_monitor().
> Problem: there is no way to cancel a monitor function.

- src/zproto_server_c.gsl
Solution: add a dummy use of engine_cancel_monitor
> Problem: pedantic compilers complain about unused engine_cancel_monitor.

- src/zproto_codec_c.gsl
Solution: use curly bracket for such fields duplication.
Avoid memory leak for doble uuid duplication also executed in set method.
> Problem: compilation error: duplicate definition if multiply same type complex fields (msg, chunk...) in message

- src/zproto_codec_java.gsl
The class uses the length of Strings instead of the length of the bytes
to calculate the frame size which causes the buffer to overflow when
multi byte chars are used.
It also does not use the ZMQ charset when getting bytes, thereby
switching between single byte and multi byte chars depending on the
underlying system.
> Problem: Java String handling is incorrect for multi byte chars

- src/zproto_codec_c.gsl
Solution: port the code from codec_v1 - I know it does bloat API a bit, however
this is complicated code, which must be generated in order to make it correct
Note: the generated code is actually tested via make check in zm-proto:  https://github.com/zmonit/zm-proto/pull/15
> Problem: want to store codec_c messages as ZPL/zconfig

- src/zproto_codec_c.gsl
Solution: note that dup returns fresh instance of class.name
> Problem: generated API model have void for dup method

- src/zproto_codec_c.gsl
> Problem: zm_proto class name hardcoded in zproto

- src/zproto_codec_c.gsl
- src/zproto_codec_c_v1.gsl
Solution: store data in appropriate zconfig_t variable
> Problem: can't build codec with strings type (unused variable)

- src/zproto_codec_c.gsl
Solution: don't do a second zframe_dup, as the class_set_routing_id
already does it. Note that other functions take ownership of the
object instead, but they take a double pointer to do it safely,
while class_set_routing_id does not so to avoid breaking API this
solution has to be adopted instead
> Problem: class_dup leaks class_routing_id

- packaging/redhat/zproto.spec
Solution: do not own /usr/bin, but all gsl files inside
> Problem: can't install zproto rpm on CentOS

- src/zproto_codec_c.gsl
Soution: if there are no fields, do not add it
> Problem: cannot compile if <message> does not contain any fields

- src/zproto_codec_c.gsl
and iterating through the hash does not have the predefined order
Solution: check, that expected values are in zhash through zhash_lookup
> Problem: zhash_first is not expected to return the element that was the first inserted

- src/zproto_codec_c.gsl
Solution: do not return NULL for messages w/o fields, allways destroy the memory
> Problem: new_zpl leaks memory for messages w/o fields

- src/zproto_codec_c.gsl
Solution: remove extra strdup, it is called by _set_$(name) method anyway
> Problem: memory leak when calling generated _dup with longstr

- src/zproto_codec_c.gsl
Solution: put } to the right place to not generate invalid code
> Problem: can't compile codec with chunk type

- src/zproto_codec_c.gsl
Solution: Remove check for string field type.
> Check of always true array address prevent compilation in pedantic mode

- src/zproto_server_c.gsl
Solution: set it to be compliant with the ZAP protocol and future
versions of libzmq
> Problem: ZAP domain not set on PLAIN auth

- src/zproto_lib_cs.gsl
(zproto_codec_cs.gsl 307) Undefined expression: cstype
error triggered when xml field of type=string contains a value attribute:
`<field name = "protocol" type = "string" value = "FILEMQ">Constant "FILEMQ"</field>`
> Allow cstype to be string

- src/zproto_server_c.gsl
for investigation purpose, it is really convenient to propagate unique identifier.
Solution : propagate it !  
Signed-off-by: Gerald Guillaume <geraldguillaume@eaton.com>
> Problem : client identifier is not propagated

- src/zproto_server_c.gsl
This bug is old, and was fixed a while in malamute project but never backported here. 
Signed-off-by: Gerald Guillaume <geraldguillaume@eaton.com>
> Problem: zsock_set_zap_domain uses NULL

- README.md
- README.txt
- src/zproto_client_c.gsl
- src/zproto_lib.gsl
Solution: adapt term virtual for recv methods, so virtual="0" will
change prototype in a following way
// virtual == 1
zmsg_t * foo_client_recv (foo_client_t *self);
// virtual == 0
int foo_client_recv (foo_client_t *self);
This is a bit similar to virtual="0" in zproto_codec_c
// virtual == 1
zmsg_t * foo_msg_recv (void *socket);
// virtual == 0
int foo_msg_recv (foo_msg_t *self, void *socket);
Defaults for codec_c and client_c are different to maintain
backward compatibility.
> Problem: zproto client works with messages with msg type only

- README.md
- README.txt
- src/zproto_client_c.gsl
- src/zproto_lib.gsl
- src/zproto_server_c.gsl
Solution: add and document protocol_dir option, which allows you to
refer to protocol from different git repository.
> Problem: can't split protocol and server (client) implementation

- src/zproto_codec_c_v1.gsl
Solution: in *_is() make sure we are inspecting a zmsg_t.
It is more complicated for *_destroy(), since classes lack a generic
magic string, checksum, CRC or some other validation that a memory
range is indeed an instance of expected structure. So left a comment.
Signed-off-by: Jim Klimov <EvgenyKlimov@eaton.com>
> Problem: no sanity check in (class)_is and (class)_destroy

- src/zproto_server_c.gsl
Add new functions engine_client_get() and engine_client_put() to allow
the application to delay the destruction of the client context. Note
that if the engine is done with the client context but the application
is not, only the structure itself is kept, but its members are freed (it
is half-dead aka zombie). The purpose is to allow the application to
match pending work with this zombie client, nothing more. In malamute,
this will be used to properly deal with pending stream traffic after
a client disconnect.
> zproto_server_c: Implement optional client context refcounting

- src/zproto_codec_c.gsl
Solution: declare variable before for loop to avoid issues with
extremely old and outdated systems
> Problem: OSX build broken due to c99 style for loop

- src/zproto_codec_java.gsl
Solution: Use the same mechanics as the C codec - that is remove the
signature and instead place the message id and topic name in-front of the
message which will be parsed against subscriptions by the zmq PUB socket.
> Problem: Java codec does not work with PUB/SUB

- src/zproto_codec_java.gsl
Solution: Check if there's remaining data before calling get()
> Problem: Exception is thrown on `needle.get()` if there's no topic data

- src/zproto_client_c.gsl
- src/zproto_codec_c.gsl
- src/zproto_lib.gsl
- src/zproto_server_c.gsl
This is mostly to allow `.hpp` or `.cpp` to be set with `header_ext` and `source_ext` variables.  O.w., even in a zproject with `use-cxx = "True"` zproto makes `.h/.c`.
A couple of const-correct fixes snuck in also.  Hopefully it's okay to include two fixes in one PR.  O.w. I can separate.
> Allow setting source/header extension similar to zproject and fix const.

- src/zproto_dot.gsl
Previously `zproto_dot.gsl` produced wrong results if there was a super-super-state.  When there was merely a super-state it duplicated the event nodes for the base state and each superstate which added unwanted (by me at least) visual complexity to the resulting graph.  
This commit produces a graphviz dot file where state inheritance is shown as a directed edge between the two states and all event nodes are shown once and only connected to the state for which they were directly defined.
The first example below shows old output on a generated server I'm working on and the second shows the new output.  It is the `connected` state which is both a super- and a sub-state.   
The original function is kept as `generate_dot_old` but maybe it should be removed?
Old `zproto_dot.gsl` output
New …
> zproto_dot fix to correctly handle levels of inheritance greater than one

- src/zproto_client_c.gsl
- src/zproto_codec_c.gsl
- src/zproto_server_c.gsl
I failed to realize that `zproto_client_c.gsl` and `zproto_server_c.gsl` do not call `expand_headers()` like `zproto_codec_c.gsl` does so they were not picking up the default setting of `header_ext` and `source_ext` that were recently introduced.  This commit sets these to default `.h/.c`.
There is also a small cast fix included to make `const` pedantic compilers happy.
> Fix regression from header_ext/source_ext addition

- src/zproto_codec_c.gsl
Solution: don't log interrupted on EAGAIN
> problem: 'interrupted' message is printed on EAGAIN

- Dockerfile
- packaging/docker/run_zproto.sh
Solution: Add a run script as entry point that takes gsl parameters
> Problem: zproto with docker image hard to use

- include/zproto_example.h
- src/zproto_codec_c.gsl
- src/zproto_example.bnf
- src/zproto_example.c
I need a way to get back an encoded message to set the new libzmq socket options ZMQ_DISCONNECT_MSG & ZMQ_HELLO_MSG
solution: add encode method that returns zframe
> problem: no way to get a encoded message out of a msg

- src/zproto_client_c.gsl
- src/zproto_codec_c.gsl
zproto_client_c.gsl:
1. count express error for class.recv
2. function assume_property not set destructor to none if property already exists.
take mlm_client.xml of project malamute for testing
zproto_codec_c.gsl
1. generate bad test code for message with msg field when class.virtual=1
take example_peer_msg.xml in src/zyre_peer_example/src for testing
> Feature fixbug

- packaging/debian/changelog
- packaging/debian/zproto.dsc.obs
Solution: change the version format to non-native as a hack, to match
OBS' debstransform usage of 1.0 format
> Problem: OBS build on sid fails

- src/zproto_client_c.gsl
- src/zproto_codec_c.gsl
1. zproto_code_c, wrong instance counter lead memory leak in unit test code when virtual is true.
2. zproto_client_c, before destroying client msgpipe,should recv & destroy all pending msg because its content contained zmsg_t pointer
> Feature codec c

- README.md
Since imatix/gsl has been archived, and development continues at [zeromq/gsl](https://github.com/zeromq/gsl), users should be pointed to the active project rather than the archived repo.
> README: Update imatix/gsl refs to zeromq/gsl
